// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmWHGEWcj8A8fdM8yNyQMAr9bsOuwdQFs',
    appId: '1:236764716905:web:e6580d091704ed719667f8',
    messagingSenderId: '236764716905',
    projectId: 'grid-93fd5',
    authDomain: 'grid-93fd5.firebaseapp.com',
    storageBucket: 'grid-93fd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz44fb_Aw7pMdAsxsc-0uv-HyV1pzmFok',
    appId: '1:236764716905:android:4dd897aa7eda18629667f8',
    messagingSenderId: '236764716905',
    projectId: 'grid-93fd5',
    storageBucket: 'grid-93fd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC21cat1NPVPn-ntS2AZQfqStGR8zvBxYw',
    appId: '1:236764716905:ios:cd2cfa3d287604d49667f8',
    messagingSenderId: '236764716905',
    projectId: 'grid-93fd5',
    storageBucket: 'grid-93fd5.appspot.com',
    iosClientId: '236764716905-8a0turl2b5lpukr8ja6inr23fc568nnc.apps.googleusercontent.com',
    iosBundleId: 'com.example.grid',
  );
}
